INSERT INTO tourscanner.nation (id, name) VALUES (59, 'Lapponia');
INSERT INTO tourscanner.nation (id, name) VALUES (101, 'Svalbard');
INSERT INTO tourscanner.nation (id, name) VALUES (3560, 'Slovacchia');
INSERT INTO tourscanner.nation (id, name) VALUES (3573, 'Lituania');
INSERT INTO tourscanner.nation (id, name) VALUES (3576, 'Lettonia');
INSERT INTO tourscanner.nation (id, name) VALUES (3745, 'Repubblica Ceca');
INSERT INTO tourscanner.nation (id, name) VALUES (3946, 'Sud Africa');
INSERT INTO tourscanner.nation (id, name) VALUES (4223, 'Tailandia');
INSERT INTO tourscanner.nation (id, name) VALUES (4555, 'Nicaragua');
INSERT INTO tourscanner.nation (id, name) VALUES (4589, 'Argentina');
INSERT INTO tourscanner.nation (id, name) VALUES (4596, 'Paraguay');
INSERT INTO tourscanner.nation (id, name) VALUES (4657, 'Ecuador');
INSERT INTO tourscanner.nation (id, name) VALUES (4682, 'Fiji');
INSERT INTO tourscanner.nation (id, name) VALUES (4684, 'Samoa');
INSERT INTO tourscanner.nation (id, name) VALUES (4689, 'Vanuatu');
INSERT INTO tourscanner.nation (id, name) VALUES (7, 'Nepal');
INSERT INTO tourscanner.nation (id, name) VALUES (6911, 'Azzorre');
INSERT INTO tourscanner.nation (id, name) VALUES (3846, 'Benin');
INSERT INTO tourscanner.nation (id, name) VALUES (89, 'Mongolia');
INSERT INTO tourscanner.nation (id, name) VALUES (447, 'Vietnam');
INSERT INTO tourscanner.nation (id, name) VALUES (6799, 'New York');
INSERT INTO tourscanner.nation (id, name) VALUES (6800, 'San Pietroburgo');
INSERT INTO tourscanner.nation (id, name) VALUES (6801, 'Cinque Terre');
INSERT INTO tourscanner.nation (id, name) VALUES (6915, 'Sofia');
INSERT INTO tourscanner.nation (id, name) VALUES (94, 'Giappone');
INSERT INTO tourscanner.nation (id, name) VALUES (2, 'Iran');
INSERT INTO tourscanner.nation (id, name) VALUES (433, 'Transilvania');
INSERT INTO tourscanner.nation (id, name) VALUES (16, 'Australia');
INSERT INTO tourscanner.nation (id, name) VALUES (6917, 'Far West');
INSERT INTO tourscanner.nation (id, name) VALUES (6948, 'Edimburgo');
INSERT INTO tourscanner.nation (id, name) VALUES (40, 'Andalusia');
INSERT INTO tourscanner.nation (id, name) VALUES (41, 'Belize');
INSERT INTO tourscanner.nation (id, name) VALUES (66, 'Alaska');
INSERT INTO tourscanner.nation (id, name) VALUES (42, 'Colombia');
INSERT INTO tourscanner.nation (id, name) VALUES (43, 'Florida');
INSERT INTO tourscanner.nation (id, name) VALUES (11, 'Cipro');
INSERT INTO tourscanner.nation (id, name) VALUES (22, 'Nuova Zelanda');
INSERT INTO tourscanner.nation (id, name) VALUES (3904, 'Seychelles');
INSERT INTO tourscanner.nation (id, name) VALUES (4018, 'Arabia Saudita');
INSERT INTO tourscanner.nation (id, name) VALUES (3887, 'Uganda');
INSERT INTO tourscanner.nation (id, name) VALUES (30, 'Scozia');
INSERT INTO tourscanner.nation (id, name) VALUES (4318, 'Corea del Sud');
INSERT INTO tourscanner.nation (id, name) VALUES (3563, 'Bulgaria');
INSERT INTO tourscanner.nation (id, name) VALUES (3703, 'Spagna');
INSERT INTO tourscanner.nation (id, name) VALUES (133, 'Sudafrica');
INSERT INTO tourscanner.nation (id, name) VALUES (84, 'Groenlandia');
INSERT INTO tourscanner.nation (id, name) VALUES (4193, 'Laos');
INSERT INTO tourscanner.nation (id, name) VALUES (92, 'Namibia');
INSERT INTO tourscanner.nation (id, name) VALUES (35, 'Emirati Arabi Uniti');
INSERT INTO tourscanner.nation (id, name) VALUES (36, 'Singapore');
INSERT INTO tourscanner.nation (id, name) VALUES (135, 'Cuba');
INSERT INTO tourscanner.nation (id, name) VALUES (124, 'Brasile');
INSERT INTO tourscanner.nation (id, name) VALUES (3798, 'Tunisia');
INSERT INTO tourscanner.nation (id, name) VALUES (10, 'Patagonia');
INSERT INTO tourscanner.nation (id, name) VALUES (56, 'Portogallo');
INSERT INTO tourscanner.nation (id, name) VALUES (6907, 'Dubai');
INSERT INTO tourscanner.nation (id, name) VALUES (6944, 'Toscana');
INSERT INTO tourscanner.nation (id, name) VALUES (12, 'Sicilia');
INSERT INTO tourscanner.nation (id, name) VALUES (13, 'Birmania');
INSERT INTO tourscanner.nation (id, name) VALUES (31, 'Tanzania');
INSERT INTO tourscanner.nation (id, name) VALUES (39, 'Cambogia');
INSERT INTO tourscanner.nation (id, name) VALUES (54, 'Hawaii');
INSERT INTO tourscanner.nation (id, name) VALUES (44, 'Corsica');
INSERT INTO tourscanner.nation (id, name) VALUES (7069, 'Tangeri Chefchaouen');
INSERT INTO tourscanner.nation (id, name) VALUES (110, 'Egitto');
INSERT INTO tourscanner.nation (id, name) VALUES (4166, 'Monaco');
INSERT INTO tourscanner.nation (id, name) VALUES (24, 'Islanda');
INSERT INTO tourscanner.nation (id, name) VALUES (6296, 'Myanmar');
INSERT INTO tourscanner.nation (id, name) VALUES (4011, 'Armenia');
INSERT INTO tourscanner.nation (id, name) VALUES (3768, 'algeria');
INSERT INTO tourscanner.nation (id, name) VALUES (3651, 'Polonia');
INSERT INTO tourscanner.nation (id, name) VALUES (4038, 'Azerbaijan');
INSERT INTO tourscanner.nation (id, name) VALUES (60, 'California');
INSERT INTO tourscanner.nation (id, name) VALUES (61, 'Guatemala');
INSERT INTO tourscanner.nation (id, name) VALUES (7082, 'Istanbul');
INSERT INTO tourscanner.nation (id, name) VALUES (62, 'Costa Rica');
INSERT INTO tourscanner.nation (id, name) VALUES (74, 'Cile');
INSERT INTO tourscanner.nation (id, name) VALUES (4387, 'Bahamas');
INSERT INTO tourscanner.nation (id, name) VALUES (3632, 'Malta');
INSERT INTO tourscanner.nation (id, name) VALUES (3851, 'Mozambico');
INSERT INTO tourscanner.nation (id, name) VALUES (3855, 'Zambia');
INSERT INTO tourscanner.nation (id, name) VALUES (7060, 'Umbria');
INSERT INTO tourscanner.nation (id, name) VALUES (7061, 'Vienna Praga');
INSERT INTO tourscanner.nation (id, name) VALUES (55, 'Canada');
INSERT INTO tourscanner.nation (id, name) VALUES (5667, 'Danimarca');
INSERT INTO tourscanner.nation (id, name) VALUES (501, 'Viaggi in Barca');
INSERT INTO tourscanner.nation (id, name) VALUES (75, 'Madagascar');
INSERT INTO tourscanner.nation (id, name) VALUES (14, 'Thailandia');
INSERT INTO tourscanner.nation (id, name) VALUES (63, 'Russia');
INSERT INTO tourscanner.nation (id, name) VALUES (93, 'Stati Uniti');
INSERT INTO tourscanner.nation (id, name) VALUES (7108, 'Napoli e Pompei');
INSERT INTO tourscanner.nation (id, name) VALUES (3, 'Turchia');
INSERT INTO tourscanner.nation (id, name) VALUES (520, 'Indonesia');
INSERT INTO tourscanner.nation (id, name) VALUES (3840, 'capo Verde');
INSERT INTO tourscanner.nation (id, name) VALUES (3898, 'Mali');
INSERT INTO tourscanner.nation (id, name) VALUES (1, 'Mondo');
INSERT INTO tourscanner.nation (id, name) VALUES (3577, 'Estonia');
INSERT INTO tourscanner.nation (id, name) VALUES (28, 'Bolivia');
INSERT INTO tourscanner.nation (id, name) VALUES (76, 'Perù');
INSERT INTO tourscanner.nation (id, name) VALUES (3596, 'Germania');
INSERT INTO tourscanner.nation (id, name) VALUES (3557, 'Albania');
INSERT INTO tourscanner.nation (id, name) VALUES (67, 'Norvegia');
INSERT INTO tourscanner.nation (id, name) VALUES (3869, 'Gibuti');
INSERT INTO tourscanner.nation (id, name) VALUES (3588, 'Francia');
INSERT INTO tourscanner.nation (id, name) VALUES (5854, 'Belgio');
INSERT INTO tourscanner.nation (id, name) VALUES (77, 'Malesia');
INSERT INTO tourscanner.nation (id, name) VALUES (18, 'Marocco');
INSERT INTO tourscanner.nation (id, name) VALUES (3824, 'Senegal');
INSERT INTO tourscanner.nation (id, name) VALUES (34, 'Finlandia');
INSERT INTO tourscanner.nation (id, name) VALUES (23, 'Irlanda');
INSERT INTO tourscanner.nation (id, name) VALUES (3908, 'Malawi');
INSERT INTO tourscanner.nation (id, name) VALUES (6173, 'Kazakistan');
INSERT INTO tourscanner.nation (id, name) VALUES (48, 'Giordania');
INSERT INTO tourscanner.nation (id, name) VALUES (3562, 'Austria');
INSERT INTO tourscanner.nation (id, name) VALUES (3933, 'Mauritius');
INSERT INTO tourscanner.nation (id, name) VALUES (3861, 'Etiopia');
INSERT INTO tourscanner.nation (id, name) VALUES (4080, 'Kyrgyzstan');
INSERT INTO tourscanner.nation (id, name) VALUES (3842, 'Guinea');
INSERT INTO tourscanner.nation (id, name) VALUES (3845, 'Ghana');
INSERT INTO tourscanner.nation (id, name) VALUES (4081, 'Turkmenistan');
INSERT INTO tourscanner.nation (id, name) VALUES (27, 'Uzbekistan');
INSERT INTO tourscanner.nation (id, name) VALUES (6177, 'Afghanistan');
INSERT INTO tourscanner.nation (id, name) VALUES (51, 'Sri Lanka');
INSERT INTO tourscanner.nation (id, name) VALUES (5039, 'SudAfrica');
INSERT INTO tourscanner.nation (id, name) VALUES (9, 'Israele');
INSERT INTO tourscanner.nation (id, name) VALUES (3825, 'Sudan');
INSERT INTO tourscanner.nation (id, name) VALUES (69, 'Grecia');
INSERT INTO tourscanner.nation (id, name) VALUES (3853, 'Botswana');
INSERT INTO tourscanner.nation (id, name) VALUES (50, 'Georgia');
INSERT INTO tourscanner.nation (id, name) VALUES (37, 'Messico');
INSERT INTO tourscanner.nation (id, name) VALUES (5817, 'Italia');
INSERT INTO tourscanner.nation (id, name) VALUES (53, 'Oman');
INSERT INTO tourscanner.nation (id, name) VALUES (52, 'Maldive');
INSERT INTO tourscanner.nation (id, name) VALUES (4137, 'Bhutan');
INSERT INTO tourscanner.nation (id, name) VALUES (29, 'Filippine');
INSERT INTO tourscanner.nation (id, name) VALUES (46, 'Cina');
INSERT INTO tourscanner.nation (id, name) VALUES (4433, 'stati Uniti');
INSERT INTO tourscanner.nation (id, name) VALUES (100, 'India');